#%RAML 1.0 NamedExample
{
    "accountNum": "1234567891",
    "atmPin": "1234",
    "ifscCode": "sbi123",
    "depositAmount": 0,
    "mailId": "viswa.vasabattula09@gmail.com",
    "contactNumber": 9398087345
  }
  