#%RAML 1.0
title: VOBS-bank-customer-account-creation
description: API for bank customer account creation
version: v1
protocols:
  - HTTP
  - HTTPS
securitySchemes:
  secure: !include Security-Schema/securityScheme.raml
securedBy:
  - secure
/createAccount:
  post:
    queryParameters:
      customerName:
        required: true
        maxLength: 45
        minLength: 4
      bank:
        required: true
        enum: # you can only select the bank in the below predefined list
          - ICICI
          - AXIS
          - HDFC
          - SBI
      type: # you can select the type in the below prdefined list of bank acct creation
        required: true
        enum:
          - savings
          - current
      branchName:
        required: true
        minLength: 4
        maxLength: 10

    body:
        application/json:
          type: !include Datatypes/inputdataType.raml
          example: !include examples/request/inputRequestexample.raml
    responses:
      201:
        body:
          application/json:
            example: !include examples/response/SuccessResponseexample.raml
      